services:
  inflearn-server:
    image: 891377394170.dkr.ecr.ap-northeast-2.amazonaws.com/inflearn-server:latest
    ports:
      - 8080:8080
    depends_on:
      mysql1:
        condition: service_healthy
      redis1:
        condition: service_healthy
  mysql1:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: park9368!
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]
      interval: 5s
      retries: 10
  redis1:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10