spring:
  jpa:
    hibernate:
      ddl-auto: update  # 데이터베이스 스키마 관리를 위한 설정
  data:
    redis:
      host: localhost
      port: 6379
  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:rss
    username: sa